### ISSUE TITLE
Algolia doc search not working

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/docs.openbeta.io#14]
### Issue
I've recently added Algolia DocSearch to the documentation site (https://docs.openbeta.io) but it's currently not working.   See https://docusaurus.io/docs/search#using-algolia-docsearch to see whether DocSearch was set it up correctly.

<img width="856" alt="Screen Shot 2022-10-14 at 9 23 37 PM" src="https://user-images.githubusercontent.com/3805254/195964668-f569ccdf-a616-450b-a6e8-157cef002d05.png">

what is DocSearch? https://docsearch.algolia.com/docs/what-is-docsearch/

**Comment by vnugent** [comment]
Hi @osaf96 can you help me with this issue?  Thanks!

**Comment by CocoisBuggy** [comment]
I'll take a look at this

**Comment by CocoisBuggy** [comment]
Hey @vnugent  was this resolved already?

![image](https://user-images.githubusercontent.com/64557383/204859517-dba28733-2844-4371-9c90-1cff0f750357.png)

Looks to be working fine

**Comment by vnugent** [comment]
I'm not sure what happened. It has started working all of a sudden.
