### ISSUE TITLE
package-lock.json should be committed

### ISSUE THREAD

**Issue by CocoisBuggy** [OpenBeta/docs.openbeta.io#15]
according to [this](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5) the lock file should probably be committed? 

Unless there is something about docusaurus in particular - in which case it should be added to gitignore

**Comment by vnugent** [comment]
It's probably an oversight.  Can you please add check in yours?  Thanks.

**Comment by CocoisBuggy** [comment]
Done, will be resolved in the next PR

**Comment by musoke** [comment]
done in https://github.com/OpenBeta/docs.openbeta.io/commit/5a0f98ebaa3815bc77000d443b677e86f6d309b7 (and subsequently deleted in favor of yarn.lock in https://github.com/OpenBeta/docs.openbeta.io/commit/b0165a3ca982e65c2ff8e2c8324221866415f40c)
