### ISSUE TITLE
Change "open-tacos" to "climb database" or climbing route catalog

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/docs.openbeta.io#20]
### Background
**open-tacos** is the code name for the [coding project](https://github.com/OpenBeta/open-tacos) that powers our main website https://openbeta.io

When the project first started, the website is also called "open-tacos" (old domain: tacos.openbeta.io).

### Proposal
To simplify our brand messaging, only use OpenBeta or the "climb database" or the climb route catalog. Retire "open tacos" in any public facing documentation.

When a coder wants to learn more contributing code, we can point them to [open-tacos](https://github.com/OpenBeta/open-tacos) repository on GitHub.  Other than that we should only use  OpenBeta to refer to our main project, the website, or the climb database or the climbing catalog.

**Comment by musoke** [comment]
So "open tacos" would refer to the front end code, and "OpenBeta" to the website and overall project?

**Comment by actuallyyun** [comment]
Using "OpenBeta" for the website sounds good to me. Will update it in the docs.

**Comment by clintonlunn** [comment]
I can probably take this if you haven't yet started @actuallyyun, I have several of the changes already done locally

**Comment by actuallyyun** [comment]
> I can probably take this if you haven't yet started @actuallyyun, I have several of the changes already done locally

Go for it!
