### ISSUE TITLE
Create a page/section listing projects made with OpenBeta services/data

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/docs.openbeta.io#42]
An example of projects  made with OSM:  https://github.com/osmlab/awesome-openstreetmap

Please add your projects by leaving the following in the comment
- Project name:
- Short description (one or two sentences):
- Website URL:

**Comment by robbyriley15** [comment]
Project name: **Snarf**
    Short description (one or two sentences): **Weather Forecasts for outdoor sports**
    Website URL: https://snarfme.com

**Comment by robbyriley15** [comment]
@vnugent You need any actual code from me for this at all or did you just need the info above?

**Comment by vnugent** [comment]
> @vnugent You need any actual code from me for this at all or did you just need the info above?

I don't have a particular format in mind so answering the 3 questions above is suffice.  If you want to add the new page to the docs site yourself, feel free to do so.

**Comment by robbyriley15** [comment]
Ok cool I can whip something up I think! 
Just to make sure I'm following you're thinking modifying the Readme.MD file to be similar to what awesome-openstreemap has for theirs?

**Comment by vnugent** [comment]
> Ok cool I can whip something up I think! Just to make sure I'm following you're thinking modifying the Readme.MD file to be similar to what awesome-openstreemap has for theirs?

Perhaps add a new page (.md file) under the **Introduction** category and place it below "Follow our progress"?

**Comment by jlaramie** [comment]
https://github.com/jlaramie/climb-bot

**Comment by robbyriley15** [comment]
Ok opened a PR for this one with a simple page
@vnugent lmk if you'd like any styling changes or otherwise

https://github.com/OpenBeta/docs.openbeta.io/pull/43
